/**
 * PoC seed data for the Upcoming candidate / offer workflow.
 *
 * These records represent shortlisted candidates who have NOT yet become Employee
 * Directory records — they intentionally live in a separate collection. In the future,
 * this data will be populated by an external interview/recruitment microapp via
 * upcomingCandidateService.syncCandidates() instead of local seed data; the shape here is
 * what that sync is expected to eventually return.
 */
export const seedUpcomingCandidates = [
  {
    id: 'cand-001',
    firstName: 'Nadia',
    lastName: 'Rahman',
    fullName: 'Nadia Rahman',
    email: 'nadia.rahman@example.com',
    positionName: 'Software Engineering',
    departmentId: 'dept-3',
    offerType: 'Paid',
    source: 'external-shortlist',
    emailStatus: 'Pending',
    responseStatus: 'Awaiting Response',
    notificationRead: true,
    shortlistedAt: '2026-08-25T09:00:00.000Z',
    emailSentAt: null,
    repliedAt: null,
    acceptedAt: null,
    rejectedAt: null,
    notes: '',
    lastEmailSubject: null,
  },
  {
    id: 'cand-002',
    firstName: 'Wei Jian',
    lastName: 'Tan',
    fullName: 'Wei Jian Tan',
    email: 'weijian.tan@example.com',
    positionName: 'Marketing & Sales',
    departmentId: 'dept-7',
    offerType: 'Unpaid',
    source: 'external-shortlist',
    emailStatus: 'Pending',
    responseStatus: 'Awaiting Response',
    notificationRead: true,
    shortlistedAt: '2026-08-27T09:00:00.000Z',
    emailSentAt: null,
    repliedAt: null,
    acceptedAt: null,
    rejectedAt: null,
    notes: '',
    lastEmailSubject: null,
  },
  {
    id: 'cand-003',
    firstName: 'Priya',
    lastName: 'Anand',
    fullName: 'Priya Anand',
    email: 'priya.anand@example.com',
    positionName: 'Product & UX',
    departmentId: 'dept-4',
    offerType: 'Paid',
    source: 'external-shortlist',
    emailStatus: 'Sent',
    responseStatus: 'Awaiting Response',
    notificationRead: true,
    shortlistedAt: '2026-08-18T09:00:00.000Z',
    emailSentAt: '2026-08-20T14:30:00.000Z',
    repliedAt: null,
    acceptedAt: null,
    rejectedAt: null,
    notes: '',
    lastEmailSubject: 'Internship Opportunity at Rizurf — Product & UX',
  },
  {
    id: 'cand-004',
    firstName: 'Faizal',
    lastName: 'Hakim',
    fullName: 'Faizal Hakim',
    email: 'faizal.hakim@example.com',
    positionName: 'Corporate Finance',
    departmentId: 'dept-8',
    offerType: 'Unpaid',
    source: 'external-shortlist',
    emailStatus: 'Sent',
    responseStatus: 'Awaiting Response',
    notificationRead: true,
    shortlistedAt: '2026-08-19T09:00:00.000Z',
    emailSentAt: '2026-08-21T11:15:00.000Z',
    repliedAt: null,
    acceptedAt: null,
    rejectedAt: null,
    notes: '',
    lastEmailSubject: 'Internship Opportunity at Rizurf — Corporate Finance',
  },
  {
    id: 'cand-005',
    firstName: 'Mohamed',
    lastName: 'Kaiser',
    fullName: 'Mohamed Kaiser',
    email: 'mohamed.kaiser@example.com',
    positionName: 'Software Engineering',
    departmentId: 'dept-3',
    offerType: 'Paid',
    source: 'external-shortlist',
    emailStatus: 'Replied',
    responseStatus: 'Awaiting Response',
    notificationRead: false,
    shortlistedAt: '2026-08-10T09:00:00.000Z',
    emailSentAt: '2026-08-12T10:00:00.000Z',
    repliedAt: '2026-09-05T16:42:00.000Z',
    acceptedAt: null,
    rejectedAt: null,
    notes: 'Replied confirming interest; sent required documents.',
    lastEmailSubject: 'Internship Opportunity at Rizurf — Software Engineering',
  },
  {
    id: 'cand-006',
    firstName: 'Su Ling',
    lastName: 'Ng',
    fullName: 'Su Ling Ng',
    email: 'suling.ng@example.com',
    positionName: 'Human Resources',
    departmentId: 'dept-5',
    offerType: 'Unpaid',
    source: 'external-shortlist',
    emailStatus: 'Replied',
    responseStatus: 'Awaiting Response',
    notificationRead: true,
    shortlistedAt: '2026-08-05T09:00:00.000Z',
    emailSentAt: '2026-08-07T09:30:00.000Z',
    repliedAt: '2026-08-14T13:05:00.000Z',
    acceptedAt: null,
    rejectedAt: null,
    notes: 'Reviewed — awaiting HR decision.',
    lastEmailSubject: 'Internship Opportunity at Rizurf — Human Resources',
  },
  {
    id: 'cand-007',
    firstName: 'Arjun',
    lastName: 'Pillai',
    fullName: 'Arjun Pillai',
    email: 'arjun.pillai@example.com',
    positionName: 'Operations',
    departmentId: 'dept-6',
    offerType: 'Paid',
    source: 'external-shortlist',
    emailStatus: 'Replied',
    responseStatus: 'Accepted',
    notificationRead: true,
    shortlistedAt: '2026-07-28T09:00:00.000Z',
    emailSentAt: '2026-07-30T09:00:00.000Z',
    repliedAt: '2026-08-04T10:20:00.000Z',
    acceptedAt: '2026-08-06T15:00:00.000Z',
    rejectedAt: null,
    notes: 'Accepted offer; awaiting onboarding conversion.',
    lastEmailSubject: 'Internship Opportunity at Rizurf — Operations',
  },
  {
    id: 'cand-008',
    firstName: 'Devi',
    lastName: 'Shankar',
    fullName: 'Devi Shankar',
    email: 'devi.shankar@example.com',
    positionName: 'Software Engineering',
    departmentId: 'dept-3',
    offerType: 'Unpaid',
    source: 'external-shortlist',
    emailStatus: 'Replied',
    responseStatus: 'Rejected',
    notificationRead: true,
    shortlistedAt: '2026-07-15T09:00:00.000Z',
    emailSentAt: '2026-07-17T09:00:00.000Z',
    repliedAt: '2026-07-22T11:00:00.000Z',
    acceptedAt: null,
    rejectedAt: '2026-07-24T09:00:00.000Z',
    notes: 'Withdrew interest; pursuing another offer.',
    lastEmailSubject: 'Internship Opportunity at Rizurf — Software Engineering',
  },
];
