export const seedDocumentTypes = [
  {
    id: 'doc-type-1',
    name: 'Employment Contract',
    code: 'CONTRACT',
    category: 'Employment',
    requiresExpiry: false,
    description: 'Standard employment agreement or letter of engagement.',
    active: true,
  },
  {
    id: 'doc-type-2',
    name: 'Identity Verification / Passport',
    code: 'ID_PASSPORT',
    category: 'Identity',
    requiresExpiry: true,
    description: 'Government identification card, passport, or birth certificate.',
    active: true,
  },
  {
    id: 'doc-type-3',
    name: 'NDA & Confidentiality Agreement',
    code: 'NDA',
    category: 'Compliance',
    requiresExpiry: false,
    description: 'Non-disclosure and intellectual property protection agreement.',
    active: true,
  },
  {
    id: 'doc-type-4',
    name: 'Academic Certificate',
    code: 'ACADEMIC_CERT',
    category: 'Qualifications',
    requiresExpiry: false,
    description: 'Higher education degree, diploma, or academic transcript.',
    active: true,
  },
  {
    id: 'doc-type-5',
    name: 'Professional Certification',
    code: 'PROF_CERT',
    category: 'Qualifications',
    requiresExpiry: true,
    description: 'Industry license, professional accreditation, or technical cert.',
    active: true,
  },
  {
    id: 'doc-type-6',
    name: 'Exit Clearance Form',
    code: 'EXIT_CLEARANCE',
    category: 'Offboarding',
    requiresExpiry: false,
    description: 'Employee departure handoff and clearance documentation.',
    active: true,
  },
];
