export const seedEmployees = [
  {
    id: 'emp-001',
    employeeId: 'RZ-1001',
    firstName: 'Tariq',
    lastName: 'Ibrahim',
    fullName: 'Tariq Ibrahim',
    workEmail: 'tariq.ibrahim@rizurf.example',
    workPhone: '+60 3-8000 1001',
    photo: 'TI',
    employeeTypeId: 'type-5',
    status: 'Active',
    startDate: '2021-01-15',
    contractEndDate: null,
    tags: ['Executive Committee', 'Founder'],
  },
  {
    id: 'emp-002',
    employeeId: 'RZ-1002',
    firstName: 'Maya',
    lastName: 'Lin',
    fullName: 'Maya Lin',
    workEmail: 'maya.lin@rizurf.example',
    workPhone: '+60 3-8000 1002',
    photo: 'ML',
    employeeTypeId: 'type-5',
    status: 'Active',
    startDate: '2021-03-01',
    contractEndDate: null,
    tags: ['Executive Committee', 'Tech Lead'],
  },
  {
    id: 'emp-003',
    employeeId: 'RZ-1003',
    firstName: 'Sarah',
    lastName: 'Abdullah',
    fullName: 'Sarah Abdullah',
    workEmail: 'sarah.abdullah@rizurf.example',
    workPhone: '+60 3-8000 1003',
    photo: 'SA',
    employeeTypeId: 'type-1',
    status: 'Active',
    startDate: '2021-06-15',
    contractEndDate: null,
    tags: ['HR Admin', 'First Aid Officer'],
  },
  {
    id: 'emp-004',
    employeeId: 'RZ-1004',
    firstName: 'Marcus',
    lastName: 'Tan',
    fullName: 'Marcus Tan',
    workEmail: 'marcus.tan@rizurf.example',
    workPhone: '+60 3-8000 1004',
    photo: 'MT',
    employeeTypeId: 'type-1',
    status: 'Active',
    startDate: '2022-02-01',
    contractEndDate: null,
    tags: ['People Manager', 'Scrum Master'],
  },
  {
    id: 'emp-005',
    employeeId: 'RZ-1005',
    firstName: 'Priyanka',
    lastName: 'Nair',
    fullName: 'Priyanka Nair',
    workEmail: 'priyanka.nair@rizurf.example',
    workPhone: '+60 3-8000 1005',
    photo: 'PN',
    employeeTypeId: 'type-1',
    status: 'Active',
    startDate: '2022-08-15',
    contractEndDate: null,
    tags: ['Core Engineering', 'Security Champ'],
  },
  {
    id: 'emp-006',
    employeeId: 'RZ-1006',
    firstName: 'Lucas',
    lastName: 'Fernandez',
    fullName: 'Lucas Fernandez',
    workEmail: 'lucas.fernandez@rizurf.example',
    workPhone: '+60 3-8000 1006',
    photo: 'LF',
    employeeTypeId: 'type-1',
    status: 'Active',
    startDate: '2022-10-01',
    contractEndDate: null,
    tags: ['Product Lead'],
  },
  {
    id: 'emp-007',
    employeeId: 'RZ-1007',
    firstName: 'Chloe',
    lastName: 'Lim',
    fullName: 'Chloe Lim',
    workEmail: 'chloe.lim@rizurf.example',
    workPhone: '+60 3-8000 1007',
    photo: 'CL',
    employeeTypeId: 'type-1',
    status: 'Active',
    startDate: '2023-01-10',
    contractEndDate: null,
    tags: ['Design System'],
  },
  {
    id: 'emp-008',
    employeeId: 'RZ-1008',
    firstName: 'Harith',
    lastName: 'Zain',
    fullName: 'Harith Zain',
    workEmail: 'harith.zain@rizurf.example',
    workPhone: '+60 3-8000 1008',
    photo: 'HZ',
    employeeTypeId: 'type-1',
    status: 'Active',
    startDate: '2023-03-15',
    contractEndDate: null,
    tags: ['Operations Lead'],
  },
  {
    id: 'emp-009',
    employeeId: 'RZ-1009',
    firstName: 'Kenneth',
    lastName: 'Ooi',
    fullName: 'Kenneth Ooi',
    workEmail: 'kenneth.ooi@rizurf.example',
    workPhone: '+60 3-8000 1009',
    photo: 'KO',
    employeeTypeId: 'type-2',
    status: 'Former',
    startDate: '2023-06-01',
    contractEndDate: '2026-05-31',
    tags: ['Alumni', 'DevOps'],
  },
  {
    id: 'emp-010',
    employeeId: 'RZ-1010',
    firstName: 'Jessica',
    lastName: 'Wong',
    fullName: 'Jessica Wong',
    workEmail: 'jessica.wong@rizurf.example',
    workPhone: '+60 3-8000 1010',
    photo: 'JW',
    employeeTypeId: 'type-1',
    status: 'Active',
    startDate: '2023-09-01',
    contractEndDate: null,
    tags: ['Marketing Lead'],
  },
  {
    id: 'emp-011',
    employeeId: 'RZ-1011',
    firstName: 'Amirah',
    lastName: 'Hashim',
    fullName: 'Amirah Hashim',
    workEmail: 'amirah.hashim@rizurf.example',
    workPhone: '+60 3-8000 1011',
    photo: 'AH',
    employeeTypeId: 'type-1',
    status: 'Active',
    startDate: '2024-01-08',
    contractEndDate: null,
    tags: ['Content Strategy'],
  },
  {
    id: 'emp-012',
    employeeId: 'RZ-1012',
    firstName: 'Rajiv',
    lastName: 'Sharma',
    fullName: 'Rajiv Sharma',
    workEmail: 'rajiv.sharma@rizurf.example',
    workPhone: '+60 3-8000 1012',
    photo: 'RS',
    employeeTypeId: 'type-1',
    status: 'Active',
    startDate: '2024-02-15',
    contractEndDate: null,
    tags: ['Finance Controller'],
  },
  {
    id: 'emp-013',
    employeeId: 'RZ-1013',
    firstName: 'Hannah',
    lastName: 'Razak',
    fullName: 'Hannah Razak',
    workEmail: 'hannah.razak@rizurf.example',
    workPhone: '+60 3-8000 1013',
    photo: 'HR',
    employeeTypeId: 'type-1',
    status: 'Onboarding',
    startDate: '2026-08-15',
    contractEndDate: null,
    tags: ['New Joiner', 'Frontend Team'],
  },
  {
    id: 'emp-014',
    employeeId: 'RZ-1014',
    firstName: 'Kevin',
    lastName: 'Heng',
    fullName: 'Kevin Heng',
    workEmail: 'kevin.heng@rizurf.example',
    workPhone: '+60 3-8000 1014',
    photo: 'KH',
    employeeTypeId: 'type-3',
    status: 'Onboarding',
    startDate: '2026-09-01',
    contractEndDate: '2027-02-28',
    tags: ['Apprentice', 'Engineering'],
  },
  {
    id: 'emp-015',
    employeeId: 'RZ-1015',
    firstName: 'Benjamin',
    lastName: 'Teoh',
    fullName: 'Benjamin Teoh',
    workEmail: 'benjamin.teoh@rizurf.example',
    workPhone: '+60 3-8000 1015',
    photo: 'BT',
    employeeTypeId: 'type-2',
    status: 'Upcoming',
    startDate: '2026-10-01',
    contractEndDate: '2027-09-30',
    tags: ['Future Hire', 'Finance'],
  },
  {
    id: 'emp-016',
    employeeId: 'RZ-1016',
    firstName: 'Farah',
    lastName: 'Mansor',
    fullName: 'Farah Mansor',
    workEmail: 'farah.mansor@rizurf.example',
    workPhone: '+60 3-8000 1016',
    photo: 'FM',
    employeeTypeId: 'type-1',
    status: 'Departing',
    startDate: '2023-04-01',
    contractEndDate: null,
    tags: ['Notice Period', 'Operations'],
  },
  {
    id: 'emp-017',
    employeeId: 'RZ-1017',
    firstName: 'Aaron',
    lastName: 'Kumar',
    fullName: 'Aaron Kumar',
    workEmail: 'aaron.kumar@rizurf.example',
    workPhone: '+60 3-8000 1017',
    photo: 'AK',
    employeeTypeId: 'type-1',
    status: 'Departing',
    startDate: '2024-05-15',
    contractEndDate: null,
    tags: ['Notice Period', 'Design'],
  },
  {
    id: 'emp-018',
    employeeId: 'RZ-1018',
    firstName: 'Daniel',
    lastName: 'Lee',
    fullName: 'Daniel Lee',
    workEmail: 'daniel.lee@rizurf.example',
    workPhone: '+60 3-8000 1018',
    photo: 'DL',
    employeeTypeId: 'type-2',
    status: 'Former',
    startDate: '2024-01-01',
    contractEndDate: '2026-06-30',
    tags: ['Alumni', 'Engineering'],
  },
];
