// The old "Activities" module (My/All/Overdue Activities pages) was removed and replaced by
// the Notes workspace. Its manual/demo activity records (formerly act-001 through act-012,
// source: 'Manual'/'System'/unlinked 'Onboarding'/'Offboarding') have been removed from this
// seed since nothing references them any more. This array remains load-bearing infrastructure,
// though: every record below is a REAL task-instance-linked activity that Onboarding/Offboarding
// plan instances (seedOnboardingInstances.js / seedOffboardingInstances.js) depend on for their
// Done/Reopen state and progress calculation via the shared activityService — do not remove
// these or the onboarding/offboarding Employee Detail pages will break.
export const seedActivities = [
  // Seeded Onboarding Task Activities for inst-001 (Hannah Razak)
  {
    id: 'act-onb-001',
    typeId: 'act-type-4',
    title: 'Prepare workstation and access credentials',
    description: 'Setup laptop, email account, internal portal access, and desk setup.',
    employeeId: 'emp-013',
    assigneeId: 'emp-004', // Marcus Tan
    dueDate: '2026-08-10',
    completed: true,
    completedAt: '2026-08-10T14:00:00Z',
    completedBy: 'emp-004',
    source: 'Onboarding',
    sourceEntityType: 'OnboardingTaskInstance',
    sourceEntityId: 'ti-001',
    createdAt: '2026-08-10T09:00:00Z',
    createdBy: 'emp-003',
    updatedAt: '2026-08-10T14:00:00Z',
  },
  {
    id: 'act-onb-002',
    typeId: 'act-type-4',
    title: 'Collect Signed Non-Disclosure Agreement',
    description: 'Verify and archive signed NDA and personal employment contract documents.',
    employeeId: 'emp-013',
    assigneeId: 'emp-003', // Sarah Abdullah
    dueDate: '2026-08-14',
    completed: true,
    completedAt: '2026-08-14T11:00:00Z',
    completedBy: 'emp-003',
    source: 'Onboarding',
    sourceEntityType: 'OnboardingTaskInstance',
    sourceEntityId: 'ti-002',
    createdAt: '2026-08-10T09:00:00Z',
    createdBy: 'emp-003',
    updatedAt: '2026-08-14T11:00:00Z',
  },
  {
    id: 'act-onb-003',
    typeId: 'act-type-3',
    title: 'Conduct HR Orientation Session',
    description: 'Welcome new hire, review company benefits, policies, and workplace overview.',
    employeeId: 'emp-013',
    assigneeId: 'emp-003',
    dueDate: '2026-08-15',
    completed: true,
    completedAt: '2026-08-15T10:30:00Z',
    completedBy: 'emp-003',
    source: 'Onboarding',
    sourceEntityType: 'OnboardingTaskInstance',
    sourceEntityId: 'ti-003',
    createdAt: '2026-08-10T09:00:00Z',
    createdBy: 'emp-003',
    updatedAt: '2026-08-15T10:30:00Z',
  },
  {
    id: 'act-onb-004',
    typeId: 'act-type-1',
    title: 'Set up payroll profile and banking info',
    description: 'Verify employee tax form, bank account details, and EPF/SOCSO credentials.',
    employeeId: 'emp-013',
    assigneeId: 'emp-013',
    dueDate: '2026-08-16',
    completed: true,
    completedAt: '2026-08-16T16:00:00Z',
    completedBy: 'emp-013',
    source: 'Onboarding',
    sourceEntityType: 'OnboardingTaskInstance',
    sourceEntityId: 'ti-004',
    createdAt: '2026-08-10T09:00:00Z',
    createdBy: 'emp-003',
    updatedAt: '2026-08-16T16:00:00Z',
  },
  {
    id: 'act-onb-005',
    typeId: 'act-type-3',
    title: 'Manager 1-on-1 Introduction & Expectations',
    description: 'Align on 30-60-90 day goals, team structure, and immediate priorities.',
    employeeId: 'emp-013',
    assigneeId: 'emp-004',
    dueDate: '2026-08-18',
    completed: false,
    completedAt: null,
    completedBy: null,
    source: 'Onboarding',
    sourceEntityType: 'OnboardingTaskInstance',
    sourceEntityId: 'ti-005',
    createdAt: '2026-08-10T09:00:00Z',
    createdBy: 'emp-003',
    updatedAt: '2026-08-10T09:00:00Z',
  },
  {
    id: 'act-onb-006',
    typeId: 'act-type-6',
    title: 'First-week check-in review',
    description: 'Check-in on initial week progress, team integration, and resolve any blockers.',
    employeeId: 'emp-013',
    assigneeId: 'emp-004',
    dueDate: '2026-08-22',
    completed: false,
    completedAt: null,
    completedBy: null,
    source: 'Onboarding',
    sourceEntityType: 'OnboardingTaskInstance',
    sourceEntityId: 'ti-006',
    createdAt: '2026-08-10T09:00:00Z',
    createdBy: 'emp-003',
    updatedAt: '2026-08-10T09:00:00Z',
  },
  {
    id: 'act-onb-007',
    typeId: 'act-type-5',
    title: 'Conduct 30-Day Onboarding Review',
    description: 'Formal 30-day feedback meeting between employee, manager, and HR.',
    employeeId: 'emp-013',
    assigneeId: 'emp-003',
    dueDate: '2026-09-14',
    completed: false,
    completedAt: null,
    completedBy: null,
    source: 'Onboarding',
    sourceEntityType: 'OnboardingTaskInstance',
    sourceEntityId: 'ti-007',
    createdAt: '2026-08-10T09:00:00Z',
    createdBy: 'emp-003',
    updatedAt: '2026-08-10T09:00:00Z',
  },

  // Seeded Onboarding Task Activities for inst-002 (Kevin Heng)
  {
    id: 'act-onb-010',
    typeId: 'act-type-4',
    title: 'Collect signed apprenticeship agreement',
    description: 'Verify educational institution endorsement and signed internship contract.',
    employeeId: 'emp-014',
    assigneeId: 'emp-003',
    dueDate: '2026-08-29',
    completed: true,
    completedAt: '2026-08-29T15:00:00Z',
    completedBy: 'emp-003',
    source: 'Onboarding',
    sourceEntityType: 'OnboardingTaskInstance',
    sourceEntityId: 'ti-010',
    createdAt: '2026-08-25T09:00:00Z',
    createdBy: 'emp-003',
    updatedAt: '2026-08-29T15:00:00Z',
  },
  {
    id: 'act-onb-011',
    typeId: 'act-type-3',
    title: 'Apprenticeship Programme & Mentor Pairing',
    description: 'Introduction to designated mentor, learning roadmap, and evaluation milestones.',
    employeeId: 'emp-014',
    assigneeId: 'emp-004',
    dueDate: '2026-09-02',
    completed: false,
    completedAt: null,
    completedBy: null,
    source: 'Onboarding',
    sourceEntityType: 'OnboardingTaskInstance',
    sourceEntityId: 'ti-011',
    createdAt: '2026-08-25T09:00:00Z',
    createdBy: 'emp-003',
    updatedAt: '2026-08-25T09:00:00Z',
  },
  {
    id: 'act-onb-012',
    typeId: 'act-type-6',
    title: '14-Day mentor check-in session',
    description: 'Review initial learning objectives, project assignments, and mentorship feedback.',
    employeeId: 'emp-014',
    assigneeId: 'emp-004',
    dueDate: '2026-09-15',
    completed: false,
    completedAt: null,
    completedBy: null,
    source: 'Onboarding',
    sourceEntityType: 'OnboardingTaskInstance',
    sourceEntityId: 'ti-012',
    createdAt: '2026-08-25T09:00:00Z',
    createdBy: 'emp-003',
    updatedAt: '2026-08-25T09:00:00Z',
  },

  // Seeded Offboarding Task Activities for inst-off-001 (Farah Mansor - Departing)
  {
    id: 'act-off-001',
    typeId: 'act-type-1',
    title: 'Conduct Handover Briefing & Document Transfer',
    description: 'Document current operational tasks, active project files, and conduct handover session with replacement/team.',
    employeeId: 'emp-016',
    assigneeId: 'emp-016',
    dueDate: '2026-08-31',
    completed: true,
    completedAt: '2026-08-31T16:00:00Z',
    completedBy: 'emp-016',
    source: 'Offboarding',
    sourceEntityType: 'OffboardingTaskInstance',
    sourceEntityId: 'ti-off-001-1',
    createdAt: '2026-08-30T00:00:00Z',
    createdBy: 'emp-003',
    updatedAt: '2026-08-31T16:00:00Z',
  },
  {
    id: 'act-off-002',
    typeId: 'act-type-5',
    title: 'Review Outstanding Projects & Pending Deliverables',
    description: 'Manager review of pending deliverables, reassigning active duties, and client handover verification.',
    employeeId: 'emp-016',
    assigneeId: 'emp-008', // Harith Zain
    dueDate: '2026-09-16',
    completed: false,
    completedAt: null,
    completedBy: null,
    source: 'Offboarding',
    sourceEntityType: 'OffboardingTaskInstance',
    sourceEntityId: 'ti-off-001-2',
    createdAt: '2026-08-30T00:00:00Z',
    createdBy: 'emp-003',
    updatedAt: '2026-08-30T00:00:00Z',
  },
  {
    id: 'act-off-003',
    typeId: 'act-type-4',
    title: 'Confirm IT Asset & Laptop Return Arrangement',
    description: 'Verify returning laptop, access badges, monitor, mobile device, and peripherals.',
    employeeId: 'emp-016',
    assigneeId: 'emp-003', // Sarah Abdullah
    dueDate: '2026-09-23',
    completed: false,
    completedAt: null,
    completedBy: null,
    source: 'Offboarding',
    sourceEntityType: 'OffboardingTaskInstance',
    sourceEntityId: 'ti-off-001-3',
    createdAt: '2026-08-30T00:00:00Z',
    createdBy: 'emp-003',
    updatedAt: '2026-08-30T00:00:00Z',
  },

  // Seeded Offboarding Task Activities for inst-off-002 (Aaron Kumar - Departing)
  {
    id: 'act-off-007',
    typeId: 'act-type-1',
    title: 'Conduct Handover Briefing & Document Transfer',
    description: 'Document current operational tasks, active project files, and conduct handover session with replacement/team.',
    employeeId: 'emp-017',
    assigneeId: 'emp-017',
    dueDate: '2026-08-16', // Overdue relative to 2026-09-02
    completed: false,
    completedAt: null,
    completedBy: null,
    source: 'Offboarding',
    sourceEntityType: 'OffboardingTaskInstance',
    sourceEntityId: 'ti-off-002-1',
    createdAt: '2026-08-15T00:00:00Z',
    createdBy: 'emp-003',
    updatedAt: '2026-08-15T00:00:00Z',
  },
  {
    id: 'act-off-008',
    typeId: 'act-type-5',
    title: 'Review Outstanding Projects & Pending Deliverables',
    description: 'Manager review of pending deliverables, reassigning active duties, and client handover verification.',
    employeeId: 'emp-017',
    assigneeId: 'emp-006', // Lucas Fernandez
    dueDate: '2026-09-01', // Overdue relative to 2026-09-02
    completed: false,
    completedAt: null,
    completedBy: null,
    source: 'Offboarding',
    sourceEntityType: 'OffboardingTaskInstance',
    sourceEntityId: 'ti-off-002-2',
    createdAt: '2026-08-15T00:00:00Z',
    createdBy: 'emp-003',
    updatedAt: '2026-08-15T00:00:00Z',
  },
];

