export const seedOnboardingPlanInstances = [
  {
    id: 'inst-001',
    planTemplateId: 'tpl-001',
    employeeId: 'emp-013', // Hannah Razak
    startedAt: '2026-08-15',
    anchorDate: '2026-08-15',
    completedAt: null,
    createdBy: 'user-4',
    createdAt: '2026-08-10T09:00:00.000Z',
  },
  {
    id: 'inst-002',
    planTemplateId: 'tpl-003',
    employeeId: 'emp-014', // Kevin Heng
    startedAt: '2026-09-01',
    anchorDate: '2026-09-01',
    completedAt: null,
    createdBy: 'user-4',
    createdAt: '2026-08-25T09:00:00.000Z',
  },
];

export const seedOnboardingTaskInstances = [
  // Task instances for Hannah Razak (inst-001)
  {
    id: 'ti-001',
    planInstanceId: 'inst-001',
    planTaskId: 'pt-001',
    activityId: 'act-onb-001',
    title: 'Prepare workstation and access credentials',
    description: 'Setup laptop, email account, internal portal access, and desk setup.',
    activityTypeId: 'act-type-4',
    assignmentRule: 'manager',
    originallyResolvedAssigneeId: 'emp-004', // Marcus Tan
    relativeOffsetDays: -5,
    originallyCalculatedDueDate: '2026-08-10',
    required: true,
    sequence: 1,
    createdAt: '2026-08-10T09:00:00.000Z',
  },
  {
    id: 'ti-002',
    planInstanceId: 'inst-001',
    planTaskId: 'pt-002',
    activityId: 'act-onb-002',
    title: 'Collect Signed Non-Disclosure Agreement',
    description: 'Verify and archive signed NDA and personal employment contract documents.',
    activityTypeId: 'act-type-4',
    assignmentRule: 'hr',
    originallyResolvedAssigneeId: 'emp-003', // Sarah Abdullah
    relativeOffsetDays: -1,
    originallyCalculatedDueDate: '2026-08-14',
    required: true,
    sequence: 2,
    createdAt: '2026-08-10T09:00:00.000Z',
  },
  {
    id: 'ti-003',
    planInstanceId: 'inst-001',
    planTaskId: 'pt-003',
    activityId: 'act-onb-003',
    title: 'Conduct HR Orientation Session',
    description: 'Welcome new hire, review company benefits, policies, and workplace overview.',
    activityTypeId: 'act-type-3',
    assignmentRule: 'hr',
    originallyResolvedAssigneeId: 'emp-003', // Sarah Abdullah
    relativeOffsetDays: 0,
    originallyCalculatedDueDate: '2026-08-15',
    required: true,
    sequence: 3,
    createdAt: '2026-08-10T09:00:00.000Z',
  },
  {
    id: 'ti-004',
    planInstanceId: 'inst-001',
    planTaskId: 'pt-004',
    activityId: 'act-onb-004',
    title: 'Set up payroll profile and banking info',
    description: 'Verify employee tax form, bank account details, and EPF/SOCSO credentials.',
    activityTypeId: 'act-type-1',
    assignmentRule: 'employee',
    originallyResolvedAssigneeId: 'emp-013', // Hannah Razak
    relativeOffsetDays: 1,
    originallyCalculatedDueDate: '2026-08-16',
    required: true,
    sequence: 4,
    createdAt: '2026-08-10T09:00:00.000Z',
  },
  {
    id: 'ti-005',
    planInstanceId: 'inst-001',
    planTaskId: 'pt-005',
    activityId: 'act-onb-005',
    title: 'Manager 1-on-1 Introduction & Expectations',
    description: 'Align on 30-60-90 day goals, team structure, and immediate priorities.',
    activityTypeId: 'act-type-3',
    assignmentRule: 'manager',
    originallyResolvedAssigneeId: 'emp-004', // Marcus Tan
    relativeOffsetDays: 3,
    originallyCalculatedDueDate: '2026-08-18',
    required: true,
    sequence: 5,
    createdAt: '2026-08-10T09:00:00.000Z',
  },
  {
    id: 'ti-006',
    planInstanceId: 'inst-001',
    planTaskId: 'pt-006',
    activityId: 'act-onb-006',
    title: 'First-week check-in review',
    description: 'Check-in on initial week progress, team integration, and resolve any blockers.',
    activityTypeId: 'act-type-6',
    assignmentRule: 'manager',
    originallyResolvedAssigneeId: 'emp-004', // Marcus Tan
    relativeOffsetDays: 7,
    originallyCalculatedDueDate: '2026-08-22',
    required: false,
    sequence: 6,
    createdAt: '2026-08-10T09:00:00.000Z',
  },
  {
    id: 'ti-007',
    planInstanceId: 'inst-001',
    planTaskId: 'pt-007',
    activityId: 'act-onb-007',
    title: 'Conduct 30-Day Onboarding Review',
    description: 'Formal 30-day feedback meeting between employee, manager, and HR.',
    activityTypeId: 'act-type-5',
    assignmentRule: 'hr',
    originallyResolvedAssigneeId: 'emp-003', // Sarah Abdullah
    relativeOffsetDays: 30,
    originallyCalculatedDueDate: '2026-09-14',
    required: true,
    sequence: 7,
    createdAt: '2026-08-10T09:00:00.000Z',
  },

  // Task instances for Kevin Heng (inst-002)
  {
    id: 'ti-010',
    planInstanceId: 'inst-002',
    planTaskId: 'pt-020',
    activityId: 'act-onb-010',
    title: 'Collect signed apprenticeship agreement',
    description: 'Verify educational institution endorsement and signed internship contract.',
    activityTypeId: 'act-type-4',
    assignmentRule: 'hr',
    originallyResolvedAssigneeId: 'emp-003', // Sarah Abdullah
    relativeOffsetDays: -3,
    originallyCalculatedDueDate: '2026-08-29',
    required: true,
    sequence: 1,
    createdAt: '2026-08-25T09:00:00.000Z',
  },
  {
    id: 'ti-011',
    planInstanceId: 'inst-002',
    planTaskId: 'pt-021',
    activityId: 'act-onb-011',
    title: 'Apprenticeship Programme & Mentor Pairing',
    description: 'Introduction to designated mentor, learning roadmap, and evaluation milestones.',
    activityTypeId: 'act-type-3',
    assignmentRule: 'manager',
    originallyResolvedAssigneeId: 'emp-004', // Marcus Tan
    relativeOffsetDays: 1,
    originallyCalculatedDueDate: '2026-09-02',
    required: true,
    sequence: 2,
    createdAt: '2026-08-25T09:00:00.000Z',
  },
  {
    id: 'ti-012',
    planInstanceId: 'inst-002',
    planTaskId: 'pt-022',
    activityId: 'act-onb-012',
    title: '14-Day mentor check-in session',
    description: 'Review initial learning objectives, project assignments, and mentorship feedback.',
    activityTypeId: 'act-type-6',
    assignmentRule: 'manager',
    originallyResolvedAssigneeId: 'emp-004', // Marcus Tan
    relativeOffsetDays: 14,
    originallyCalculatedDueDate: '2026-09-15',
    required: true,
    sequence: 3,
    createdAt: '2026-08-25T09:00:00.000Z',
  },
];
