/**
 * PoC seed data for the Upcoming candidate / offer workflow.
 *
 * These records represent shortlisted candidates who have NOT yet become Employee
 * Directory records — they intentionally live in a separate collection. In the future,
 * this data will be populated by an external interview/recruitment microapp via
 * upcomingCandidateService.syncCandidates() instead of local seed data; the shape here is
 * what that sync is expected to eventually return.
 */
export const seedUpcomingCandidates = [
  {
    id: 'cand-001',
    firstName: 'Nadia',
    lastName: 'Rahman',
    fullName: 'Nadia Rahman',
    email: 'nadia.rahman@example.com',
    positionName: 'Software Engineering',
    departmentId: 'dept-3',
    offerType: 'Paid',
    source: 'external-shortlist',
    emailStatus: 'Pending',
    responseStatus: 'Awaiting Response',
    notificationRead: true,
    shortlistedAt: '2026-08-25T09:00:00.000Z',
    emailSentAt: null,
    repliedAt: null,
    acceptedAt: null,
    rejectedAt: null,
    notes: '',
    lastEmailSubject: null,
  },
  {
    id: 'cand-002',
    firstName: 'Wei Jian',
    lastName: 'Tan',
    fullName: 'Wei Jian Tan',
    email: 'weijian.tan@example.com',
    positionName: 'Marketing & Sales',
    departmentId: 'dept-7',
    offerType: 'Unpaid',
    source: 'external-shortlist',
    emailStatus: 'Pending',
    responseStatus: 'Awaiting Response',
    notificationRead: true,
    shortlistedAt: '2026-08-27T09:00:00.000Z',
    emailSentAt: null,
    repliedAt: null,
    acceptedAt: null,
    rejectedAt: null,
    notes: '',
    lastEmailSubject: null,
  },
  {
    id: 'cand-003',
    firstName: 'Priya',
    lastName: 'Anand',
    fullName: 'Priya Anand',
    email: 'priya.anand@example.com',
    positionName: 'Product & UX',
    departmentId: 'dept-4',
    offerType: 'Paid',
    source: 'external-shortlist',
    emailStatus: 'Sent',
    responseStatus: 'Awaiting Response',
    notificationRead: true,
    shortlistedAt: '2026-08-18T09:00:00.000Z',
    emailSentAt: '2026-08-20T14:30:00.000Z',
    repliedAt: null,
    acceptedAt: null,
    rejectedAt: null,
    notes: '',
    lastEmailSubject: 'Internship Opportunity at Rizurf — Product & UX',
  },
  {
    id: 'cand-004',
    firstName: 'Faizal',
    lastName: 'Hakim',
    fullName: 'Faizal Hakim',
    email: 'faizal.hakim@example.com',
    positionName: 'Corporate Finance',
    departmentId: 'dept-8',
    offerType: 'Unpaid',
    source: 'external-shortlist',
    emailStatus: 'Sent',
    responseStatus: 'Awaiting Response',
    notificationRead: true,
    shortlistedAt: '2026-08-19T09:00:00.000Z',
    emailSentAt: '2026-08-21T11:15:00.000Z',
    repliedAt: null,
    acceptedAt: null,
    rejectedAt: null,
    notes: '',
    lastEmailSubject: 'Internship Opportunity at Rizurf — Corporate Finance',
  },
  {
    id: 'cand-005',
    firstName: 'Mohamed',
    lastName: 'Kaiser',
    fullName: 'Mohamed Kaiser',
    email: 'mohamed.kaiser@example.com',
    positionName: 'Software Engineering',
    departmentId: 'dept-3',
    offerType: 'Paid',
    source: 'external-shortlist',
    emailStatus: 'Replied',
    responseStatus: 'Awaiting Response',
    notificationRead: false,
    shortlistedAt: '2026-08-10T09:00:00.000Z',
    emailSentAt: '2026-08-12T10:00:00.000Z',
    repliedAt: '2026-09-05T16:42:00.000Z',
    acceptedAt: null,
    rejectedAt: null,
    notes: 'Replied confirming interest; sent required documents.',
    lastEmailSubject: 'Internship Opportunity at Rizurf — Software Engineering',
    replyMessage: "Hi, thank you for the offer — I'm very interested and happy to accept the terms. I've attached my IC copy and latest transcript as requested. Please let me know if you need anything else before my start date.",
  },
  {
    id: 'cand-006',
    firstName: 'Su Ling',
    lastName: 'Ng',
    fullName: 'Su Ling Ng',
    email: 'suling.ng@example.com',
    positionName: 'Human Resources',
    departmentId: 'dept-5',
    offerType: 'Unpaid',
    source: 'external-shortlist',
    emailStatus: 'Replied',
    responseStatus: 'Awaiting Response',
    notificationRead: false,
    shortlistedAt: '2026-08-05T09:00:00.000Z',
    emailSentAt: '2026-08-07T09:30:00.000Z',
    repliedAt: '2026-09-12T10:15:00.000Z',
    acceptedAt: null,
    rejectedAt: null,
    notes: 'Replied with updated availability; not yet reviewed.',
    lastEmailSubject: 'Internship Opportunity at Rizurf — Human Resources',
    replyMessage: "Hello, thanks for reaching out! I can start a week later than the date listed, on the 21st instead — is that still workable? Let me know and I'll confirm right away.",
  },
  {
    id: 'cand-007',
    firstName: 'Arjun',
    lastName: 'Pillai',
    fullName: 'Arjun Pillai',
    email: 'arjun.pillai@example.com',
    positionName: 'Operations',
    departmentId: 'dept-6',
    offerType: 'Paid',
    source: 'external-shortlist',
    emailStatus: 'Replied',
    responseStatus: 'Accepted',
    notificationRead: true,
    shortlistedAt: '2026-07-28T09:00:00.000Z',
    emailSentAt: '2026-07-30T09:00:00.000Z',
    repliedAt: '2026-08-04T10:20:00.000Z',
    acceptedAt: '2026-08-06T15:00:00.000Z',
    rejectedAt: null,
    notes: 'Accepted offer; awaiting onboarding conversion.',
    lastEmailSubject: 'Internship Opportunity at Rizurf — Operations',
    replyMessage: "Thank you so much for the opportunity — I'd love to accept! Really excited to join the Operations team. Let me know the next steps for onboarding.",
  },
  {
    id: 'cand-008',
    firstName: 'Devi',
    lastName: 'Shankar',
    fullName: 'Devi Shankar',
    email: 'devi.shankar@example.com',
    positionName: 'Software Engineering',
    departmentId: 'dept-3',
    offerType: 'Unpaid',
    source: 'external-shortlist',
    emailStatus: 'Replied',
    responseStatus: 'Rejected',
    notificationRead: true,
    shortlistedAt: '2026-07-15T09:00:00.000Z',
    emailSentAt: '2026-07-17T09:00:00.000Z',
    repliedAt: '2026-07-22T11:00:00.000Z',
    acceptedAt: null,
    rejectedAt: '2026-07-24T09:00:00.000Z',
    notes: 'Withdrew interest; pursuing another offer.',
    lastEmailSubject: 'Internship Opportunity at Rizurf — Software Engineering',
    replyMessage: "Hi, thank you for the offer, but I've decided to accept a different position that's a closer fit for what I'm looking for right now. I appreciate the opportunity and hope our paths cross again.",
  },
  {
    id: 'cand-009',
    firstName: 'Aiman',
    lastName: 'Yusof',
    fullName: 'Aiman Yusof',
    email: 'aiman.yusof@example.com',
    positionName: 'Marketing & Sales',
    departmentId: 'dept-7',
    offerType: 'Paid',
    source: 'external-shortlist',
    emailStatus: 'Replied',
    responseStatus: 'Awaiting Response',
    notificationRead: false,
    shortlistedAt: '2026-08-22T09:00:00.000Z',
    emailSentAt: '2026-08-24T09:30:00.000Z',
    repliedAt: '2026-09-14T08:50:00.000Z',
    acceptedAt: null,
    rejectedAt: null,
    notes: 'Replied asking about start-date flexibility; not yet reviewed.',
    lastEmailSubject: 'Internship Opportunity at Rizurf — Marketing & Sales',
    replyMessage: "Hi there, this sounds great! Quick question before I confirm — is there any flexibility on the start date? I have a prior commitment that wraps up the first week of September.",
  },
];
