export const seedEmployeeTags = [
  { id: 'tag-1', name: 'Executive Committee', category: 'Committee', color: '#129FA9', active: true },
  { id: 'tag-2', name: 'Founder', category: 'General', color: '#8B5CF6', active: true },
  { id: 'tag-3', name: 'Tech Lead', category: 'Role/Skill', color: '#3B82F6', active: true },
  { id: 'tag-4', name: 'HR Admin', category: 'Operational', color: '#059669', active: true },
  { id: 'tag-5', name: 'First Aid Officer', category: 'Operational', color: '#D97706', active: true },
  { id: 'tag-6', name: 'People Manager', category: 'Role/Skill', color: '#2563EB', active: true },
  { id: 'tag-7', name: 'Scrum Master', category: 'Role/Skill', color: '#0E848D', active: true },
  { id: 'tag-8', name: 'Core Engineering', category: 'Role/Skill', color: '#6366F1', active: true },
  { id: 'tag-9', name: 'Security Champ', category: 'Operational', color: '#DC2626', active: true },
  { id: 'tag-10', name: 'Product Lead', category: 'Role/Skill', color: '#0284C7', active: true },
  { id: 'tag-11', name: 'Design System', category: 'Role/Skill', color: '#EC4899', active: true },
  { id: 'tag-12', name: 'Operations Lead', category: 'Role/Skill', color: '#F59E0B', active: true },
  { id: 'tag-13', name: 'Alumni', category: 'Status Tag', color: '#64748B', active: true },
  { id: 'tag-14', name: 'DevOps', category: 'Role/Skill', color: '#10B981', active: true },
  { id: 'tag-15', name: 'Marketing Lead', category: 'Role/Skill', color: '#8B5CF6', active: true },
  { id: 'tag-16', name: 'Content Strategy', category: 'Role/Skill', color: '#6366F1', active: true },
  { id: 'tag-17', name: 'Finance Controller', category: 'Role/Skill', color: '#059669', active: true },
  { id: 'tag-18', name: 'New Joiner', category: 'Status Tag', color: '#0E848D', active: true },
  { id: 'tag-19', name: 'Frontend Team', category: 'Role/Skill', color: '#3B82F6', active: true },
  { id: 'tag-20', name: 'Apprentice', category: 'Status Tag', color: '#D97706', active: true },
  { id: 'tag-21', name: 'Engineering', category: 'Role/Skill', color: '#6366F1', active: true },
  { id: 'tag-22', name: 'Future Hire', category: 'Status Tag', color: '#2563EB', active: true },
  { id: 'tag-23', name: 'Finance', category: 'Role/Skill', color: '#059669', active: true },
  { id: 'tag-24', name: 'Notice Period', category: 'Status Tag', color: '#F59E0B', active: true },
  { id: 'tag-25', name: 'Operations', category: 'Role/Skill', color: '#64748B', active: true },
  { id: 'tag-26', name: 'Design', category: 'Role/Skill', color: '#EC4899', active: true },
];
