export const seedOffboardingPlanInstances = [
  {
    id: 'inst-off-001',
    planTemplateId: 'tpl-off-001',
    employeeId: 'emp-016', // Farah Mansor (Departing, Final Working Date 2026-09-30)
    startedAt: '2026-09-30',
    anchorDate: '2026-09-30',
    completedAt: null,
    createdBy: 'emp-003', // Sarah Abdullah (HR)
    createdAt: '2026-08-30T00:00:00.000Z',
  },
  {
    id: 'inst-off-002',
    planTemplateId: 'tpl-off-001',
    employeeId: 'emp-017', // Aaron Kumar (Departing, Final Working Date 2026-09-15)
    startedAt: '2026-09-15',
    anchorDate: '2026-09-15',
    completedAt: null,
    createdBy: 'emp-003', // Sarah Abdullah (HR)
    createdAt: '2026-08-15T00:00:00.000Z',
  },
];

export const seedOffboardingTaskInstances = [
  // Instance 1: Farah Mansor (emp-016), Anchor Date: 2026-09-30
  {
    id: 'ti-off-001-1',
    planInstanceId: 'inst-off-001',
    planTaskId: 'pt-off-001',
    activityId: 'act-off-001',
    title: 'Conduct Handover Briefing & Document Transfer',
    description: 'Document current operational tasks, active project files, and conduct handover session with replacement/team.',
    activityTypeId: 'act-type-1',
    assignmentRule: 'employee',
    originallyResolvedAssigneeId: 'emp-016',
    relativeOffsetDays: -30,
    originallyCalculatedDueDate: '2026-08-31',
    required: true,
    sequence: 1,
    createdAt: '2026-08-30T00:00:00.000Z',
  },
  {
    id: 'ti-off-001-2',
    planInstanceId: 'inst-off-001',
    planTaskId: 'pt-off-002',
    activityId: 'act-off-002',
    title: 'Review Outstanding Projects & Pending Deliverables',
    description: 'Manager review of pending deliverables, reassigning active duties, and client handover verification.',
    activityTypeId: 'act-type-5',
    assignmentRule: 'manager',
    originallyResolvedAssigneeId: 'emp-008', // Harith Zain (Operations Lead)
    relativeOffsetDays: -14,
    originallyCalculatedDueDate: '2026-09-16',
    required: true,
    sequence: 2,
    createdAt: '2026-08-30T00:00:00.000Z',
  },
  {
    id: 'ti-off-001-3',
    planInstanceId: 'inst-off-001',
    planTaskId: 'pt-off-003',
    activityId: 'act-off-003',
    title: 'Confirm IT Asset & Laptop Return Arrangement',
    description: 'Verify returning laptop, access badges, monitor, mobile device, and peripherals.',
    activityTypeId: 'act-type-4',
    assignmentRule: 'hr',
    originallyResolvedAssigneeId: 'emp-003', // Sarah Abdullah
    relativeOffsetDays: -7,
    originallyCalculatedDueDate: '2026-09-23',
    required: true,
    sequence: 3,
    createdAt: '2026-08-30T00:00:00.000Z',
  },
  {
    id: 'ti-off-001-4',
    planInstanceId: 'inst-off-001',
    planTaskId: 'pt-off-004',
    activityId: 'act-off-004',
    title: 'Complete Exit Clearance Form & Expense Claims',
    description: 'Submit outstanding travel expenses, medical receipts, and complete signed exit clearance document.',
    activityTypeId: 'act-type-4',
    assignmentRule: 'employee',
    originallyResolvedAssigneeId: 'emp-016',
    relativeOffsetDays: -3,
    originallyCalculatedDueDate: '2026-09-27',
    required: true,
    sequence: 4,
    createdAt: '2026-08-30T00:00:00.000Z',
  },
  {
    id: 'ti-off-001-5',
    planInstanceId: 'inst-off-001',
    planTaskId: 'pt-off-005',
    activityId: 'act-off-005',
    title: 'Conduct Formal Exit Interview',
    description: 'HR exit interview session to gather feedback, discuss career reasons, and explain post-employment benefits.',
    activityTypeId: 'act-type-3',
    assignmentRule: 'hr',
    originallyResolvedAssigneeId: 'emp-003',
    relativeOffsetDays: -1,
    originallyCalculatedDueDate: '2026-09-29',
    required: true,
    sequence: 5,
    createdAt: '2026-08-30T00:00:00.000Z',
  },
  {
    id: 'ti-off-001-6',
    planInstanceId: 'inst-off-001',
    planTaskId: 'pt-off-006',
    activityId: 'act-off-006',
    title: 'Deactivate Internal Systems & Portal Access',
    description: 'Revoke corporate email account, SSO credentials, VPN access, and internal portal roles on final working day.',
    activityTypeId: 'act-type-1',
    assignmentRule: 'hr',
    originallyResolvedAssigneeId: 'emp-003',
    relativeOffsetDays: 0,
    originallyCalculatedDueDate: '2026-09-30',
    required: true,
    sequence: 6,
    createdAt: '2026-08-30T00:00:00.000Z',
  },

  // Instance 2: Aaron Kumar (emp-017), Anchor Date: 2026-09-15
  {
    id: 'ti-off-002-1',
    planInstanceId: 'inst-off-002',
    planTaskId: 'pt-off-001',
    activityId: 'act-off-007',
    title: 'Conduct Handover Briefing & Document Transfer',
    description: 'Document current operational tasks, active project files, and conduct handover session with replacement/team.',
    activityTypeId: 'act-type-1',
    assignmentRule: 'employee',
    originallyResolvedAssigneeId: 'emp-017',
    relativeOffsetDays: -30,
    originallyCalculatedDueDate: '2026-08-16',
    required: true,
    sequence: 1,
    createdAt: '2026-08-15T00:00:00.000Z',
  },
  {
    id: 'ti-off-002-2',
    planInstanceId: 'inst-off-002',
    planTaskId: 'pt-off-002',
    activityId: 'act-off-008',
    title: 'Review Outstanding Projects & Pending Deliverables',
    description: 'Manager review of pending deliverables, reassigning active duties, and client handover verification.',
    activityTypeId: 'act-type-5',
    assignmentRule: 'manager',
    originallyResolvedAssigneeId: 'emp-006', // Lucas Fernandez (Head of Product)
    relativeOffsetDays: -14,
    originallyCalculatedDueDate: '2026-09-01',
    required: true,
    sequence: 2,
    createdAt: '2026-08-15T00:00:00.000Z',
  },
  {
    id: 'ti-off-002-3',
    planInstanceId: 'inst-off-002',
    planTaskId: 'pt-off-003',
    activityId: 'act-off-009',
    title: 'Confirm IT Asset & Laptop Return Arrangement',
    description: 'Verify returning laptop, access badges, monitor, mobile device, and peripherals.',
    activityTypeId: 'act-type-4',
    assignmentRule: 'hr',
    originallyResolvedAssigneeId: 'emp-003',
    relativeOffsetDays: -7,
    originallyCalculatedDueDate: '2026-09-08',
    required: true,
    sequence: 3,
    createdAt: '2026-08-15T00:00:00.000Z',
  },
  {
    id: 'ti-off-002-4',
    planInstanceId: 'inst-off-002',
    planTaskId: 'pt-off-005',
    activityId: 'act-off-010',
    title: 'Conduct Formal Exit Interview',
    description: 'HR exit interview session to gather feedback, discuss career reasons, and explain post-employment benefits.',
    activityTypeId: 'act-type-3',
    assignmentRule: 'hr',
    originallyResolvedAssigneeId: 'emp-003',
    relativeOffsetDays: -1,
    originallyCalculatedDueDate: '2026-09-14',
    required: true,
    sequence: 4,
    createdAt: '2026-08-15T00:00:00.000Z',
  },
];
