export const seedPositions = [
  {
    id: 'pos-1',
    name: 'Chief Executive Officer',
    departmentId: 'dept-1',
    defaultManagerId: null,
    defaultScheduleId: 'sched-1',
    defaultLocationId: 'loc-1',
    active: true,
  },
  {
    id: 'pos-2',
    name: 'Chief Technology Officer',
    departmentId: 'dept-2',
    defaultManagerId: 'emp-001',
    defaultScheduleId: 'sched-1',
    defaultLocationId: 'loc-1',
    active: true,
  },
  {
    id: 'pos-3',
    name: 'HR Director',
    departmentId: 'dept-5',
    defaultManagerId: 'emp-001',
    defaultScheduleId: 'sched-1',
    defaultLocationId: 'loc-1',
    active: true,
  },
  {
    id: 'pos-4',
    name: 'Engineering Manager',
    departmentId: 'dept-3',
    defaultManagerId: 'emp-002',
    defaultScheduleId: 'sched-2',
    defaultLocationId: 'loc-1',
    active: true,
  },
  {
    id: 'pos-5',
    name: 'Senior Full Stack Engineer',
    departmentId: 'dept-3',
    defaultManagerId: 'emp-004',
    defaultScheduleId: 'sched-2',
    defaultLocationId: 'loc-1',
    active: true,
  },
  {
    id: 'pos-6',
    name: 'Frontend Software Engineer',
    departmentId: 'dept-3',
    defaultManagerId: 'emp-004',
    defaultScheduleId: 'sched-2',
    defaultLocationId: 'loc-1',
    active: true,
  },
  {
    id: 'pos-7',
    name: 'Head of Product',
    departmentId: 'dept-4',
    defaultManagerId: 'emp-002',
    defaultScheduleId: 'sched-2',
    defaultLocationId: 'loc-1',
    active: true,
  },
  {
    id: 'pos-8',
    name: 'UI/UX Product Designer',
    departmentId: 'dept-4',
    defaultManagerId: 'emp-006',
    defaultScheduleId: 'sched-2',
    defaultLocationId: 'loc-3',
    active: true,
  },
  {
    id: 'pos-9',
    name: 'Head of Operations',
    departmentId: 'dept-6',
    defaultManagerId: 'emp-001',
    defaultScheduleId: 'sched-1',
    defaultLocationId: 'loc-1',
    active: true,
  },
  {
    id: 'pos-10',
    name: 'Operations Specialist',
    departmentId: 'dept-6',
    defaultManagerId: 'emp-008',
    defaultScheduleId: 'sched-3',
    defaultLocationId: 'loc-1',
    active: true,
  },
  {
    id: 'pos-11',
    name: 'Marketing Manager',
    departmentId: 'dept-7',
    defaultManagerId: 'emp-001',
    defaultScheduleId: 'sched-1',
    defaultLocationId: 'loc-1',
    active: true,
  },
  {
    id: 'pos-12',
    name: 'Digital Marketing Specialist',
    departmentId: 'dept-7',
    defaultManagerId: 'emp-010',
    defaultScheduleId: 'sched-1',
    defaultLocationId: 'loc-1',
    active: true,
  },
  {
    id: 'pos-13',
    name: 'Corporate Finance Manager',
    departmentId: 'dept-8',
    defaultManagerId: 'emp-001',
    defaultScheduleId: 'sched-1',
    defaultLocationId: 'loc-1',
    active: true,
  },
  {
    id: 'pos-14',
    name: 'Senior Accountant',
    departmentId: 'dept-8',
    defaultManagerId: 'emp-012',
    defaultScheduleId: 'sched-1',
    defaultLocationId: 'loc-1',
    active: true,
  },
  {
    id: 'pos-15',
    name: 'Software Engineering Intern',
    departmentId: 'dept-3',
    defaultManagerId: 'emp-004',
    defaultScheduleId: 'sched-1',
    defaultLocationId: 'loc-1',
    active: true,
  },
];
